// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b090bcf9ba9f756ec8ff53e7707269729172a325/moment/moment.d.ts
declare var moment: moment.MomentStatic;
