#!/bin/bash

SESSIONNAME="$(pwd)"
tmux has-session -t $SESSIONNAME

if [ $? != 0 ]
then
    tmux new-session -d -s $SESSIONNAME
    tmux rename-window 'dev-env'
    tmux select-window -t 'dev-env'
    tmux send-keys 'npm run dev' 'C-m'
    tmux split-window -h -t 'dev-env'
    tmux send-keys 'npm run mock-server' 'C-m'
    tmux split-window -v -t 'dev-env'
    tmux send-keys 'npm run proxy' 'C-m'
fi

tmux -2 attach-session -t $SESSIONNAME
